- name: get vault secrets
  hosts: localhost
  tasks:
    - name: get secrets
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret=common/data/ssh token=hvs.RTDXtStxH3G1DIGzKWmDmojA url=https://3.84.209.151:8200 validate_certs=false')}}"

