format_version: 10
pipelines:
  vault:
    group: expense
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/devps23/learn-expense
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
          TF_VAR_vault_token: "AES:IvAycXISaHk/adtR6T4YSQ==:Imo/EPUW0N+BviYa8qdqsodVK71ef/aeq7lCJK10o7I="

    stages:
    - DEV:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          vault-job:
            timeout: 0
            tasks:
            - exec: { command: terraform, arguments: ["init"], run_if: passed }
            - exec: { command: terraform, arguments: ["apply","-auto-approve"], run_if: passed }


